= There Is No Spoon

An introduction to some dangerous assumptions while building software systems.

The format is a reveal.js presentation mastered in AsciiDoc.

== `./prepare`
Downloads reveal.js for offline use.

== `./build`
Creates the presentation HTML.

The generated HTML includes http://livejs.com/[live.js] which may be helpful
while editing *if* the page is served over HTTP and not a `file://` URL.

NOTE: When editing a specific slide, the browser will need a manual reload before
live.js works (related to the option to create a URL per slide).

== `./watch_and_rebuild` [Linux only]

Run the build when the file is saved.

Also starts an HTTP server to serve the generated content (http://localhost:8000).

NOTE: Uses `inotifywatch` and `python3` which may need to be installed.

== `./package`
ZIPs up the HTML + dependencies into a sharable archive.

== PDF Document

Open the HTML *in Chrome/Chomium* with `?print-pdf` appended to the URL, then use
the 'Print' dialog.

* http://localhost:8000/there-is-no-spoon.html?print-pdf#/
* file:///home/tony/ws/PERSONAL/presentations/there-is-no-spoon/there-is-no-spoon.html?print-pdf#/

NOTE: If you want to include speaker notes in your export, you can append
`showNotes=true` to the query string.
